=== HUSAINTRIVEDI52/xml-sem5/Unit 1/Email.dtd
<?xml version="1.0" encoding="UTF-8"?>
	<!ELEMENT Email (From,To,Content)>
	<!ELEMENT From (#PCDATA)>
	<!ELEMENT To (#PCDATA)>
	<!ELEMENT Content (Person,exercises,course)>
	<!ELEMENT Person (#PCDATA)>
	<!ELEMENT exercises (exercise)>
	<!ELEMENT exercise (Topic,Description)>
	<!ELEMENT Topic (#PCDATA)>
	<!ELEMENT Description (#PCDATA)>
	<!ELEMENT course (#PCDATA)>

=== HUSAINTRIVEDI52/xml-sem5/Unit 1/Email.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE Email SYSTEM "Email.dtd">
	<Email>
		<From></From>
		<To></To>
		<Content>
			<Person></Person>
			<exercises> 
				<exercise>
					<Topic></Topic>
					<Description></Description>
				</exercise>
			</exercises>
					<course></course>
		</Content>

	</Email>
