=== HUSAINTRIVEDI52/xml-sem5/Unit 1/Students.dtd
<!ELEMENT Students (Name,ID,Plan)>
<!ELEMENT Name (Fname,Lname)>
<!ELEMENT Fname (#PCDATA)>
<!ELEMENT Lname (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Plan (Courses)>
<!ATTLIST  Courses  year CDATA #REQUIRED>
<!ELEMENT Courses (Course)>
<!ELEMENT Course (CName,ShortName,Record+)>
<!ELEMENT CName (#PCDATA)>
<!ELEMENT ShortName (#PCDATA)>
<!ELEMENT Record  (Grade,Date)>
<!ELEMENT Grade (#PCDATA)>
<!ELEMENT Date (#PCDATA)>

=== HUSAINTRIVEDI52/xml-sem5/202300319010105/Students.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE Students SYSTEM "Students.dtd">
<Students>
		<Name>
			<Fname></Fname>
			<Lname></Lname>
		</Name>
		<ID></ID>
		<Plan>
			<Courses year="2022">
				<Course>
					<CName></CName>
				<ShortName></ShortName>
				<Record>
					<Grade></Grade>
					<Date></Date>
				</Record>
				</Course>
			</Courses>
		</Plan>
</Students>
