=== HUSAINTRIVEDI52/xml-sem5/Final exam practice/Unit 2/1.dtd
<!ELEMENT PersonalInfo (Roll_no,Name,Address,Mobile,DOB,Age,Qualification)>
<!ELEMENT Roll_no (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Mobile (#PCDATA)>
<!ELEMENT DOB (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Qualification (#PCDATA)>

=== HUSAINTRIVEDI52/xml-sem5/Final exam practice/Unit 2/1.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE PersonalInfo SYSTEM "1.dtd">
	<PersonalInfo>
		<Roll_no>123</Roll_no>
		<Name>Husain</Name>
		<Address>Ahmedabad</Address>
		<Mobile>7698379853</Mobile>
		<DOB>24-08-2005</DOB>
		<Age>45</Age>
		<Qualification>BCA</Qualification>
	</PersonalInfo>
