=== HUSAINTRIVEDI52/xml-sem5/Final exam practice/Unit 2/4.dtd
<!ELEMENT Student (Student_Name,Personal_Info,Result)>
<!ELEMENT Student_Name (#PCDATA)>
<!ELEMENT Personal_Info (Address,Birthdate,Gender,Mobile)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Birthdate (#PCDATA)>
<!ELEMENT Gender (Male | Female )>
<!ELEMENT Male EMPTY>
<!ELEMENT Female EMPTY>
<!ELEMENT Mobile (#PCDATA)>
<!ELEMENT Result (Total,Percentage,Grade)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Percentage (#PCDATA)>
<!ELEMENT Grade (Pass |First |Dist |Second |Fail )>
<!ELEMENT Pass EMPTY>
<!ELEMENT First EMPTY>
<!ELEMENT Dist EMPTY>
<!ELEMENT Second EMPTY>
<!ELEMENT Fail EMPTY>

=== HUSAINTRIVEDI52/xml-sem5/Final exam practice/Unit 2/4.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE Student SYSTEM "4.dtd">
<Student>
	<Student_Name>Husain TRivedi</Student_Name>
	<Personal_Info>
		<Address>Ahmedabad</Address>
		<Birthdate>24082005</Birthdate>
		<Gender><Male/></Gender>
		<Mobile>77963145</Mobile>
	</Personal_Info>
	<Result>
		<Total>500</Total>
		<Percentage>55</Percentage>
		<Grade><Pass/></Grade>
	</Result>
</Student>
