=== HUSAINTRIVEDI52/xml-sem5/Final exam practice/Unit 2/6.dtd
<!ELEMENT Student (Name,ID,Plan)>
<!ELEMENT Name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Plan (courses)>
<!ATTLIST courses year CDATA #REQUIRED>
<!ELEMENT courses (course)>
<!ELEMENT course (name,shortname,record)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT shortname (#PCDATA)>
<!ELEMENT record (grade,date)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== HUSAINTRIVEDI52/xml-sem5/Final exam practice/Unit 2/6.xml
<?xml version="1.0" encoding="UTF-8"?> 
	<!DOCTYPE Student SYSTEM "6.dtd">
	<Student>
		<Name>
			<fname>Husain</fname>
			<lname>Trivedi</lname>
		</Name>
		<ID>14</ID>
		<Plan>
			<courses year="1111">
				<course>
					<name></name>
					<shortname></shortname>
					<record>
						<grade></grade>
						<date></date>
					</record>
				</course>
			</courses>
		</Plan>
	</Student>
