=== HUSAINTRIVEDI52/xml-sem5/202300319010105/PersonalInfo.dtd
<!ELEMENT PersonalInfo (RollNo,Name,Address,MobileNo,DOB,Age,Qualification)>	
<!ELEMENT RollNo (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT MobileNo (#PCDATA)>
<!ELEMENT DOB (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Qualification (#PCDATA)>

=== HUSAINTRIVEDI52/xml-sem5/Unit 1/PersonalInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE PersonalInfo SYSTEM "PersonalInfo.dtd">	
	<PersonalInfo>	
		<RollNo>d</RollNo>
		<Name>e</Name>
		<Address>e</Address>
		<MobileNo>e</MobileNo>
		<DOB>e</DOB>
		<Age>e</Age>
		<Qualification>e</Qualification>
	</PersonalInfo>
