=== HUSAINTRIVEDI52/xml-sem5/202300319010105/Student.dtd
<!ELEMENT Student (StudentName,PersnolInfo,Result)>
<!ELEMENT StudentName (#PCDATA)>
<!ELEMENT PersnolInfo (Address,BirthDate,Gender,Mobile)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT BirthDate (#PCDATA)>
<!ELEMENT Gender (#PCDATA)>
<!ELEMENT Mobile (#PCDATA)>
<!ELEMENT Result (Total,Percentage,Grade)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Percentage (#PCDATA)>
<!ELEMENT Grade (#PCDATA)>
<!ATTLIST PersnolInfo Gender (Male|Female) #REQUIRED>
<!ATTLIST Grade value (Pass| First|Dist|Second|Fail) #REQUIRED>

=== HUSAINTRIVEDI52/xml-sem5/Unit 1/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE Student SYSTEM "Student.dtd">

<Student>
	<StudentName></StudentName>
	<PersnolInfo Gender="Male">
			<Address></Address>
			<BirthDate></BirthDate>
			<Gender></Gender>
			<Mobile></Mobile>
	</PersnolInfo>
	<Result>
		<Total></Total>
		<Percentage></Percentage>
		<Grade value="Pass"></Grade>
	</Result>
</Student>
